name: dev
channels:
  - conda-forge
dependencies:
  - pynvim
  - python
  - python-lsp-server
  - pylsp-mypy
  - pylsp-rope
  - lua-language-server
  - marksman
  - bash-language-server
  - dockerfile-language-server-nodejs
  - jupyter
  - google-generativeai
  - pip
  - pip:
    - aider-install
